In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.shape

(891, 12)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**3 Adding few columns for demonstrating data issues**

In [5]:
np.arange(1, 891 + 1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
       365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
       378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,
       391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,
       404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,
       417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429,
       430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
       443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455,
       456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468,
       469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481,
       482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
       495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507,
       508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533,
       534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
       547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559,
       560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
       612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
       638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650,
       651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663,
       664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676,
       677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702,
       703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715,
       716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728,
       729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741,
       742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754,
       755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767,
       768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780,
       781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793,
       794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806,
       807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819,
       820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832,
       833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845,
       846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858,
       859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871,
       872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884,
       885, 886, 887, 888, 889, 890, 891])

In [6]:
# ID like column for testing purposes
df["Passenger_Id_Test"] = np.arange(1, len(df) + 1)

# Constant column for testing purposes
df["Constant_Column"] = 1

df["Embarked_Town"] = df["Embarked"].map({
    "S": "Southampton",
    "C": "Cherbourg",
    "Q": "Queenstown"
})

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Passenger_Id_Test,Constant_Column,Embarked_Town
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,1,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,1,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,1,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,1,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,1,Southampton

In [8]:
df["Embarked_Town_Dirty"] = df["Embarked_Town"].copy()

In [9]:
# Select a few random rows (only non missing)
sample_idx = df["Embarked_Town_Dirty"].dropna().sample(6, random_state=42).index

In [10]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [11]:
# apply simple dirty transformations
df.loc[sample_idx[0:2], "Embarked_Town_Dirty"] = df.loc[sample_idx[0:2], "Embarked_Town_Dirty"].str.upper()
df.loc[sample_idx[2:4], "Embarked_Town_Dirty"] = df.loc[sample_idx[0:2], "Embarked_Town_Dirty"].str.strip().apply(lambda x: f" {x} ")
df.loc[sample_idx[4:6], "Embarked_Town_Dirty"] = "unknown"

In [12]:
df.iloc[585]

PassengerId                            586
Survived                                 1
Pclass                                   1
Name                   Taussig, Miss. Ruth
Sex                                 female
Age                                   18.0
SibSp                                    0
Parch                                    2
Ticket                              110413
Fare                                 79.65
Cabin                                  E68
Embarked                                 S
Passenger_Id_Test                      586
Constant_Column                          1
Embarked_Town                  Southampton
Embarked_Town_Dirty                unknown
Name: 585, dtype: object

In [13]:
df.iloc[281]["Embarked_Town_Dirty"]

'SOUTHAMPTON'

In [14]:
df.shape

(891, 16)

In [15]:
df.dtypes

PassengerId              int64
Survived                 int64
Pclass                   int64
Name                       str
Sex                        str
Age                    float64
SibSp                    int64
Parch                    int64
Ticket                     str
Fare                   float64
Cabin                      str
Embarked                   str
Passenger_Id_Test        int64
Constant_Column          int64
Embarked_Town              str
Embarked_Town_Dirty        str
dtype: object

In [16]:
df.nunique()

PassengerId            891
Survived                 2
Pclass                   3
Name                   891
Sex                      2
Age                     88
SibSp                    7
Parch                    7
Ticket                 681
Fare                   248
Cabin                  147
Embarked                 3
Passenger_Id_Test      891
Constant_Column          1
Embarked_Town            3
Embarked_Town_Dirty      5
dtype: int64

In [17]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Passenger_Id_Test,Constant_Column
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

**Missing values summary**

In [18]:
missing_count = df.isna().sum().sort_values(ascending=False)
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({"missing_count": missing_count, "missing_percent": missing_percent})

print("Missing values summary")
missing_summary

Missing values summary

                     missing_count  missing_percent
Cabin                          687        77.104377
Age                            177        19.865320
Embarked_Town_Dirty              4         0.448934
Embarked_Town                    2         0.224467
Embarked                         2         0.224467
PassengerId                      0         0.000000
Pclass                           0         0.000000
Survived                         0         0.000000
Parch                            0         0.000000
SibSp                            0         0.000000
Sex                              0         0.000000
Name                             0         0.000000
Ticket                           0         0.000000
Fare                             0         0.000000
Constant_Column                  0         0.000000
Passenger_Id_Test                0         0.000000

**Duplicates**

In [19]:
duplicaties_mask = df.duplicated()
num_duplicates = duplicaties_mask.sum()

print("Number of duplicate rows:", num_duplicates)

# if you want to remove duplicates:
# df_no_duplicates = df.drop_duplicates()

Number of duplicate rows: 0

In [21]:
expected_types = {
    "Survived": "int64",
    "Pclass": "int64",
    "Sex": "category",
    "Age": "float64",
    "Fare": "float64",
    "Embarked_Town": "category",
    "PassengerId": "int64",
}

print("Data types validation")
for col, expected in expected_types.items():
    actual = df[col].dtype
    if actual != expected:
        print(f"Column '{col}' has type '{actual}', expected '{expected}'")
    else:
        print(f"Column '{col}' has the expected type '{expected}'")

Data types validation
Column 'Survived' has the expected type 'int64'
Column 'Pclass' has the expected type 'int64'
Column 'Sex' has type 'str', expected 'category'
Column 'Age' has the expected type 'float64'
Column 'Fare' has the expected type 'float64'
Column 'Embarked_Town' has type 'str', expected 'category'
Column 'PassengerId' has the expected type 'int64'

**Const and Quasi-Comstant columns**

In [ ]:
n_rows = len(df)
nunique = df.nunique()

constant_cols = nunique[nunique == 1].index.to_list()
print("Constant columns: ", constant_cols)

# quasi const columns
quasi_const_cols = []

for col in df.columns:
    top_freq = df[col].value_counts(normalize=True, dropna=False).values[0]
    if top_freq > 0.95 and col not in constant_cols:
        quasi_const_cols.append(col)
        
print("Quasi constant columns are (top values more than 95 percent: )", quasi_const_cols)

Constant columns:  ['Constant_Column']
Quasi constant columns are (top values more than 95 percent)

In [23]:
df.nunique()

PassengerId            891
Survived                 2
Pclass                   3
Name                   891
Sex                      2
Age                     88
SibSp                    7
Parch                    7
Ticket                 681
Fare                   248
Cabin                  147
Embarked                 3
Passenger_Id_Test      891
Constant_Column          1
Embarked_Town            3
Embarked_Town_Dirty      5
dtype: int64

In [ ]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [27]:
df["Survived"].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

**Id like columns**

In [28]:
n_rows = len(df)

id_like_cols = []

for col in df.columns:
    if df[col].nunique(dropna=False) == n_rows:
        id_like_cols.append(col)
        
print("Id like columns:", id_like_cols)

Id like columns: ['PassengerId', 'Name', 'Passenger_Id_Test']

**String inconsistency**

In [35]:
object_cols = df.select_dtypes(include=["object"]).columns.to_list()
print("Object or category based columns", object_cols)

# Simple clean: strip spaces convert to lower case
df["Embarked_Town_Clean"] = (
    df["Embarked_Town_Dirty"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace("unknown", np.nan)
)

Object or category based columns ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Embarked_Town', 'Embarked_Town_Dirty']

C:\Users\jones\AppData\Local\Temp\ipykernel_15080\2488017810.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include=["object"]).columns.to_list()

In [36]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [37]:
df.iloc[281]

PassengerId                                         282
Survived                                              0
Pclass                                                3
Name                   Olsson, Mr. Nils Johan Goransson
Sex                                                male
Age                                                28.0
SibSp                                                 0
Parch                                                 0
Ticket                                           347464
Fare                                             7.8542
Cabin                                               NaN
Embarked                                              S
Passenger_Id_Test                                   282
Constant_Column                                       1
Embarked_Town                               Southampton
Embarked_Town_Dirty                         SOUTHAMPTON
Embarked_Town_Clean                         southampton
Name: 281, dtype: object

**High null columns**

In [40]:
high_null_threashold = 0.4 # 40% are missing in a column

high_null_cols = missing_summary[missing_summary["missing_percent"] >= high_null_threashold * 100]

print("Columns with high missing percentage:")
print(high_null_cols)

Columns with high missing percentage:
       missing_count  missing_percent
Cabin            687        77.104377

**High zero columns (numeric)**

In [41]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.to_list()
zero_share = {}

for col in numeric_cols:
    zero_share[col] = (df[col] == 0).mean()

zero_share_series = pd.Series(zero_share).sort_values(ascending=False)
print(zero_share)

print("-"*50)

high_zero_threashold = 0.8
high_zero_cols = zero_share_series[zero_share_series >= high_zero_threashold]
print("Numeric columns with many zeros:", high_zero_cols)

{'PassengerId': np.float64(0.0), 'Survived': np.float64(0.6161616161616161), 'Pclass': np.float64(0.0), 'Age': np.float64(0.0), 'SibSp': np.float64(0.6823793490460157), 'Parch': np.float64(0.7609427609427609), 'Fare': np.float64(0.016835016835016835), 'Passenger_Id_Test': np.float64(0.0), 'Constant_Column': np.float64(0.0)}
--------------------------------------------------
Numeric columns with many zeros: Series([], dtype: float64)